### ISSUE TITLE
[improvements] Models improvements

### ISSUE THREAD

**Issue by davebulaval** [GRAAL-Research/deepparse#57]
### Data augmentations:

- [x] `,` in addresses (#56)
~- [ ] order noise [WIP]~
- [x] incomplete address noise (no postal code, no city) (#78)

### Tags improvement:

~~- [ ] Adding a Country tag~~
- [x] Retrain new tags (#81)

### New models:
- [x] attention model (#105)

### Smaller models
- [x] half size for hidden size (#103)

**Comment by davebulaval** [comment]
ETA januray
